language: node_js
node_js:
      - "8.9.0"
install:
     - npm install
script:
     - npm run test
after_success:
      - npm run test:cov
      - "npm install coveralls && cat ./coverage/lcov.info | coveralls"
notifications:
  email:
    - adrien.deperetti.freelance@gmail.com